### ISSUE TITLE
Is SF building tiny homes in order to alleviate the homelessness issue?

### ISSUE THREAD

**Issue by genidma** [SFDigitalServices/sf-dahlia-web#2061]
Apologize if this is not the avenue to ask this question. I searched for affordable housing and stumbled across your page. Thank you.

**Comment by alulabeshue-sfgov** [comment]
Hi @genidma, thank you for your feedback. We have a `your feedback` link on our [website](https://housing.sfgov.org/) which would be the place to leave this feedback.
